package com.wisnu.kurniawan.wallee.model

enum class CategoryType {
    MONTHLY_FEE,
    ADMIN_FEE,
    PETS,
    DONATION,
    EDUCATION,
    FINANCIAL,
    ENTERTAINMENT,
    CHILDREN_NEEDS,
    HOUSEHOLD_NEEDS,
    SPORT,
    OTHERS,
    FOOD,
    PARKING,
    FUEL,
    MOVIE,
    AUTOMOTIVE,
    TAX,
    INCOME,
    BUSINESS_EXPENSES,
    SELF_CARE,
    LOAN,
    SERVICE,
    SHOPPING,
    BILLS,
    TAXI,
    CASH_WITHDRAWAL,
    PHONE,
    TOP_UP,
    PUBLIC_TRANSPORTATION,
    TRAVEL,
    UNCATEGORIZED,
}
