package com.wisnu.kurniawan.wallee.model

enum class CategoryType(val value: String) {
    MONTHLY_FEE("monthly_fee"),
    ADMIN_FEE("admin_fee"),
    PETS("pets"),
    DONATION("donation"),
    EDUCATION("education"),
    FINANCIAL("financial"),
    ENTERTAINMENT("entertainment"),
    CHILDREN_NEEDS("children_needs"),
    HOUSEHOLD_NEEDS("household_needs"),
    SPORT("sport"),
    OTHERS("others"),
    FOOD("food"),
    PARKING("parking"),
    FUEL("fuel"),
    MOVIE("movie"),
    AUTOMOTIVE("automotive"),
    TAX("tax"),
    INCOME("income"),
    BUSINESS_EXPENSES("business_expense"),
    SELF_CARE("self_care"),
    LOAN("loan"),
    SERVICE("service"),
    SHOPPING("shopping"),
    BILLS("bilss"),
    TAXI("taxi"),
    CASH_WITHDRAWAL("cash_withdrawal"),
    PHONE("phone"),
    TOP_UP("top_up"),
    PUBLIC_TRANSPORTATION("public_transportation"),
    TRAVEL("travel"),
    UNCATEGORIZED("uncategorized"),
}
