package com.wisnu.kurniawan.wallee.foundation.currency

/**
 * Currency code follow ISO 4217
 * https://en.wikipedia.org/wiki/ISO_4217
 */
class CurrencyData(
    val code: String,
    val num: Int,
    val scale: Int,
    val name: String,
    val symbol: String,
    val countries: List<Country>
)

/**
 * Country code follow ISO 3166
 * https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
 *
 * Lang code follow ISO 639 alpha-2
 * https://en.wikipedia.org/wiki/ISO_639-1
 */
data class Country(
    val code: String,
    val lang: String,
    val name: String
)

val CURRENCY_DATA = listOf(
    CurrencyData(code="AED", num=784, scale=2, name="United Arab Emirates dirham", symbol="د.إ.", countries=listOf(Country(code="AE", lang="ar", name="United Arab Emirates"))),
    CurrencyData(code="AFN", num=971, scale=2, name="Afghan afghani", symbol="Af", countries=listOf(Country(code="AF", lang="uz", name="Afghanistan"))),
    CurrencyData(code="ALL", num=8, scale=2, name="Albanian lek", symbol="L", countries=listOf(Country(code="AL", lang="sq", name="Albania"))),
    CurrencyData(code="AMD", num=51, scale=2, name="Armenian dram", symbol="֏", countries=listOf(Country(code="AM", lang="hy", name="Armenia"))),
    CurrencyData(code="ANG", num=532, scale=2, name="Netherlands Antillean guilder", symbol="ƒ", countries=listOf(Country(code="CW", lang="nl", name="Curaçao"), Country(code="SX", lang="nl", name="Sint Maarten"))),
    CurrencyData(code="AOA", num=973, scale=2, name="Angolan kwanza", symbol="Kz", countries=listOf(Country(code="AO", lang="pt", name="Angola"))),
    CurrencyData(code="ARS", num=32, scale=2, name="Argentine peso", symbol="AR$", countries=listOf(Country(code="AR", lang="es", name="Argentina"))),
    CurrencyData(code="AUD", num=36, scale=2, name="Australian dollar", symbol="AU$", countries=listOf(Country(code="AU", lang="en", name="Australia"), Country(code="CX", lang="en", name="Christmas Island"), Country(code="Keeling", lang="", name="Cocos  Islands (CC)"), Country(code="HM", lang="", name="Heard Island and McDonald Islands"), Country(code="KI", lang="en", name="Kiribati"), Country(code="NR", lang="en", name="Nauru"), Country(code="NF", lang="en", name="Norfolk Island"), Country(code="TV", lang="en", name="Tuvalu"))),
    CurrencyData(code="AWG", num=533, scale=2, name="Aruban florin", symbol="ƒ", countries=listOf(Country(code="AW", lang="nl", name="Aruba"))),
    CurrencyData(code="AZN", num=944, scale=2, name="Azerbaijani manat", symbol="ман", countries=listOf(Country(code="AZ", lang="az", name="Azerbaijan"))),
    CurrencyData(code="BAM", num=977, scale=2, name="Bosnia and Herzegovina convertible mark", symbol="KM", countries=listOf(Country(code="BA", lang="hr", name="Bosnia and Herzegovina"))),
    CurrencyData(code="BBD", num=52, scale=2, name="Barbados dollar", symbol="BBD$", countries=listOf(Country(code="BB", lang="en", name="Barbados"))),
    CurrencyData(code="BDT", num=50, scale=2, name="Bangladeshi taka", symbol="৳", countries=listOf(Country(code="BD", lang="ccp", name="Bangladesh"))),
    CurrencyData(code="BGN", num=975, scale=2, name="Bulgarian lev", symbol="лв.", countries=listOf(Country(code="BG", lang="bg", name="Bulgaria"))),
    CurrencyData(code="BHD", num=48, scale=3, name="Bahraini dinar", symbol="BD", countries=listOf(Country(code="BH", lang="ar", name="Bahrain"))),
    CurrencyData(code="BIF", num=108, scale=0, name="Burundian franc", symbol="FBu", countries=listOf(Country(code="BI", lang="rn", name="Burundi"))),
    CurrencyData(code="BMD", num=60, scale=2, name="Bermudian dollar", symbol="$", countries=listOf(Country(code="BM", lang="en", name="Bermuda"))),
    CurrencyData(code="BND", num=96, scale=2, name="Brunei dollar", symbol="B$", countries=listOf(Country(code="BN", lang="ms", name="Brunei"))),
    CurrencyData(code="BOB", num=68, scale=2, name="Boliviano", symbol="Bs.", countries=listOf(Country(code="BO", lang="qu", name="Bolivia"))),
    CurrencyData(code="BRL", num=986, scale=2, name="Brazilian real", symbol="R$", countries=listOf(Country(code="BR", lang="es", name="Brazil"))),
    CurrencyData(code="BSD", num=44, scale=2, name="Bahamian dollar", symbol="$", countries=listOf(Country(code="BS", lang="en", name="Bahamas"))),
    CurrencyData(code="BTN", num=64, scale=2, name="Bhutanese ngultrum", symbol="Nu.", countries=listOf(Country(code="BT", lang="dz", name="Bhutan"))),
    CurrencyData(code="BWP", num=72, scale=2, name="Botswana pula", symbol="P", countries=listOf(Country(code="BW", lang="en", name="Botswana"))),
    CurrencyData(code="BYN", num=933, scale=2, name="Belarusian ruble", symbol="Br", countries=listOf(Country(code="BY", lang="ru", name="Belarus"))),
    CurrencyData(code="BZD", num=84, scale=2, name="Belize dollar", symbol="BZ$", countries=listOf(Country(code="BZ", lang="es", name="Belize"))),
    CurrencyData(code="CAD", num=124, scale=2, name="Canadian dollar", symbol="CA$", countries=listOf(Country(code="CA", lang="en", name="Canada"))),
    CurrencyData(code="CDF", num=976, scale=2, name="Congolese franc", symbol="FC", countries=listOf(Country(code="CD", lang="lu", name="Democratic Republic of the Congo"))),
    CurrencyData(code="CHF", num=756, scale=2, name="Swiss franc", symbol="Fr.", countries=listOf(Country(code="CH", lang="en", name="Switzerland"), Country(code="LI", lang="de", name="Liechtenstein"))),
    CurrencyData(code="CLP", num=152, scale=0, name="Chilean peso", symbol="CL$", countries=listOf(Country(code="CL", lang="es", name="Chile"))),
    CurrencyData(code="COP", num=170, scale=2, name="Colombian peso", symbol="CO$", countries=listOf(Country(code="CO", lang="es", name="Colombia"))),
    CurrencyData(code="CRC", num=188, scale=2, name="Costa Rican colon", symbol="₡", countries=listOf(Country(code="CR", lang="es", name="Costa Rica"))),
    CurrencyData(code="CUC", num=931, scale=2, name="Cuban convertible peso", symbol="CUC$", countries=listOf(Country(code="CU", lang="es", name="Cuba"))),
    CurrencyData(code="CUP", num=192, scale=2, name="Cuban peso", symbol="${'$'}MN", countries=listOf(Country(code="CU", lang="es", name="Cuba"))),
    CurrencyData(code="CVE", num=132, scale=2, name="Cape Verdean escudo", symbol="CV$", countries=listOf(Country(code="CV", lang="pt", name="Cabo Verde"))),
    CurrencyData(code="CZK", num=203, scale=2, name="Czech koruna", symbol="Kč", countries=listOf(Country(code="CZ", lang="cs", name="Czechia"))),
    CurrencyData(code="DJF", num=262, scale=0, name="Djiboutian franc", symbol="Fdj", countries=listOf(Country(code="DJ", lang="ar", name="Djibouti"))),
    CurrencyData(code="DKK", num=208, scale=2, name="Danish krone", symbol="kr.", countries=listOf(Country(code="DK", lang="fo", name="Denmark"), Country(code="FO", lang="fo", name="Faroe Islands"), Country(code="GL", lang="da", name="Greenland"))),
    CurrencyData(code="DOP", num=214, scale=2, name="Dominican peso", symbol="RD$", countries=listOf(Country(code="DO", lang="es", name="Dominican Republic"))),
    CurrencyData(code="DZD", num=12, scale=2, name="Algerian dinar", symbol="DA", countries=listOf(Country(code="DZ", lang="ar", name="Algeria"))),
    CurrencyData(code="EGP", num=818, scale=2, name="Egyptian pound", symbol="E£", countries=listOf(Country(code="EG", lang="ar", name="Egypt"))),
    CurrencyData(code="ERN", num=232, scale=2, name="Eritrean nakfa", symbol="Nkf", countries=listOf(Country(code="ER", lang="ar", name="Eritrea"))),
    CurrencyData(code="ETB", num=230, scale=2, name="Ethiopian birr", symbol="Br", countries=listOf(Country(code="ET", lang="so", name="Ethiopia"))),
    CurrencyData(code="EUR", num=978, scale=2, name="Euro", symbol="€", countries=listOf(Country(code="AX", lang="sv", name="Åland Islands"), Country(code="EU", lang="", name="European Union"), Country(code="AD", lang="ca", name="Andorra"), Country(code="AT", lang="de", name="Austria"), Country(code="BE", lang="nl", name="Belgium"), Country(code="CY", lang="tr", name="Cyprus"), Country(code="EE", lang="et", name="Estonia"), Country(code="FI", lang="smn", name="Finland"), Country(code="FR", lang="br", name="France"), Country(code="TF", lang="", name="French Southern and Antarctic Lands"), Country(code="DE", lang="en", name="Germany"), Country(code="GR", lang="el", name="Greece"), Country(code="GP", lang="fr", name="Guadeloupe"), Country(code="IE", lang="ga", name="Ireland"), Country(code="IT", lang="fur", name="Italy"), Country(code="LV", lang="lv", name="Latvia"), Country(code="LT", lang="lt", name="Lithuania"), Country(code="LU", lang="de", name="Luxembourg"), Country(code="MT", lang="mt", name="Malta"), Country(code="GF", lang="fr", name="French Guiana"), Country(code="MQ", lang="fr", name="Martinique"), Country(code="YT", lang="fr", name="Mayotte"), Country(code="MC", lang="fr", name="Monaco"), Country(code="ME", lang="sr", name="Montenegro"), Country(code="NL", lang="nds", name="Netherlands"), Country(code="PT", lang="pt", name="Portugal"), Country(code="RE", lang="fr", name="Réunion"), Country(code="BL", lang="fr", name="Saint Barthélemy"), Country(code="MF", lang="fr", name="Saint Martin"), Country(code="PM", lang="fr", name="Saint Pierre and Miquelon"), Country(code="SM", lang="it", name="San Marino"), Country(code="SK", lang="sk", name="Slovakia"), Country(code="SI", lang="en", name="Slovenia"), Country(code="ES", lang="gl", name="Spain"), Country(code="VA", lang="it", name="Vatican City"))),
    CurrencyData(code="FJD", num=242, scale=2, name="Fijian dollar|Fiji dollar", symbol="FJ$", countries=listOf(Country(code="FJ", lang="en", name="Fiji"))),
    CurrencyData(code="FKP", num=238, scale=2, name="Falkland Islands pound", symbol="FK£", countries=listOf(Country(code="FK", lang="en", name="Falkland Islands"))),
    CurrencyData(code="GBP", num=826, scale=2, name="Pound sterling", symbol="£", countries=listOf(Country(code="GB", lang="cy", name="United Kingdom"), Country(code="IM", lang="en", name="Isle of Man"), Country(code="JE", lang="en", name="Jersey"), Country(code="GG", lang="en", name="Guernsey"), Country(code="SH-TA", lang="", name="Tristan da Cunha"))),
    CurrencyData(code="GEL", num=981, scale=2, name="Georgian lari", symbol="₾", countries=listOf(Country(code="GE", lang="ka", name="Georgia"))),
    CurrencyData(code="GHS", num=936, scale=2, name="Ghanaian cedi", symbol="GH₵", countries=listOf(Country(code="GH", lang="ak", name="Ghana"))),
    CurrencyData(code="GIP", num=292, scale=2, name="Gibraltar pound", symbol="£", countries=listOf(Country(code="GI", lang="en", name="Gibraltar"))),
    CurrencyData(code="GMD", num=270, scale=2, name="Gambian dalasi", symbol="D", countries=listOf(Country(code="GM", lang="en", name="Gambia"))),
    CurrencyData(code="GNF", num=324, scale=0, name="Guinean franc", symbol="FG", countries=listOf(Country(code="GN", lang="ff", name="Guinea"))),
    CurrencyData(code="GTQ", num=320, scale=2, name="Guatemalan quetzal", symbol="Q", countries=listOf(Country(code="GT", lang="es", name="Guatemala"))),
    CurrencyData(code="GYD", num=328, scale=2, name="Guyanese dollar", symbol="G$", countries=listOf(Country(code="GY", lang="en", name="Guyana"))),
    CurrencyData(code="HKD", num=344, scale=2, name="Hong Kong dollar", symbol="HK$", countries=listOf(Country(code="HK", lang="en", name="Hong Kong"))),
    CurrencyData(code="HNL", num=340, scale=2, name="Honduran lempira", symbol="L", countries=listOf(Country(code="HN", lang="es", name="Honduras"))),
    CurrencyData(code="HRK", num=191, scale=2, name="Croatian kuna", symbol="kn", countries=listOf(Country(code="HR", lang="hr", name="Croatia"))),
    CurrencyData(code="HTG", num=332, scale=2, name="Haitian gourde", symbol="G", countries=listOf(Country(code="HT", lang="fr", name="Haiti"))),
    CurrencyData(code="HUF", num=348, scale=2, name="Hungarian forint", symbol="Ft", countries=listOf(Country(code="HU", lang="hu", name="Hungary"))),
    CurrencyData(code="IDR", num=360, scale=2, name="Indonesian rupiah", symbol="Rp", countries=listOf(Country(code="ID", lang="in", name="Indonesia"))),
    CurrencyData(code="ILS", num=376, scale=2, name="Israeli new shekel", symbol="₪", countries=listOf(Country(code="IL", lang="iw", name="Israel"))),
    CurrencyData(code="INR", num=356, scale=2, name="Indian rupee", symbol="Rs.", countries=listOf(Country(code="IN", lang="ccp", name="India"), Country(code="BT", lang="dz", name="Bhutan"))),
    CurrencyData(code="IQD", num=368, scale=3, name="Iraqi dinar", symbol="د.ع.", countries=listOf(Country(code="IQ", lang="ckb", name="Iraq"))),
    CurrencyData(code="IRR", num=364, scale=2, name="Iranian rial", symbol="﷼", countries=listOf(Country(code="IR", lang="ckb", name="Iran"))),
    CurrencyData(code="ISK", num=352, scale=0, name="Icelandic króna", symbol="kr", countries=listOf(Country(code="IS", lang="is", name="Iceland"))),
    CurrencyData(code="JMD", num=388, scale=2, name="Jamaican dollar", symbol="J$", countries=listOf(Country(code="JM", lang="en", name="Jamaica"))),
    CurrencyData(code="JOD", num=400, scale=3, name="Jordanian dinar", symbol="JD", countries=listOf(Country(code="JO", lang="ar", name="Jordan"))),
    CurrencyData(code="JPY", num=392, scale=0, name="Japanese yen", symbol="¥", countries=listOf(Country(code="JP", lang="ja", name="Japan"))),
    CurrencyData(code="KES", num=404, scale=2, name="Kenyan shilling", symbol="KSh", countries=listOf(Country(code="KE", lang="mas", name="Kenya"))),
    CurrencyData(code="KGS", num=417, scale=2, name="Kyrgyzstani som", symbol="с", countries=listOf(Country(code="KG", lang="ky", name="Kyrgyzstan"))),
    CurrencyData(code="KHR", num=116, scale=2, name="Cambodian riel", symbol="៛", countries=listOf(Country(code="KH", lang="km", name="Cambodia"))),
    CurrencyData(code="KMF", num=174, scale=0, name="Comoro franc", symbol="CF", countries=listOf(Country(code="KM", lang="fr", name="Comoros"))),
    CurrencyData(code="KPW", num=408, scale=2, name="North Korean won", symbol="₩", countries=listOf(Country(code="KP", lang="ko", name="North Korea"))),
    CurrencyData(code="KRW", num=410, scale=0, name="South Korean won", symbol="₩", countries=listOf(Country(code="KR", lang="ko", name="South Korea"))),
    CurrencyData(code="KWD", num=414, scale=3, name="Kuwaiti dinar", symbol="KD", countries=listOf(Country(code="KW", lang="ar", name="Kuwait"))),
    CurrencyData(code="KYD", num=136, scale=2, name="Cayman Islands dollar", symbol="CI$", countries=listOf(Country(code="KY", lang="en", name="Cayman Islands"))),
    CurrencyData(code="KZT", num=398, scale=2, name="Kazakhstani tenge", symbol="₸", countries=listOf(Country(code="KZ", lang="ru", name="Kazakhstan"))),
    CurrencyData(code="LAK", num=418, scale=2, name="Lao kip", symbol="₭N", countries=listOf(Country(code="LA", lang="lo", name="Laos"))),
    CurrencyData(code="LBP", num=422, scale=2, name="Lebanese pound", symbol="LL.", countries=listOf(Country(code="LB", lang="ar", name="Lebanon"))),
    CurrencyData(code="LKR", num=144, scale=2, name="Sri Lankan rupee", symbol="Rs.", countries=listOf(Country(code="LK", lang="si", name="Sri Lanka"))),
    CurrencyData(code="LRD", num=430, scale=2, name="Liberian dollar", symbol="L$", countries=listOf(Country(code="LR", lang="vai", name="Liberia"))),
    CurrencyData(code="LSL", num=426, scale=2, name="Lesotho loti", symbol="L", countries=listOf(Country(code="LS", lang="en", name="Lesotho"))),
    CurrencyData(code="LYD", num=434, scale=3, name="Libyan dinar", symbol="LD", countries=listOf(Country(code="LY", lang="ar", name="Libya"))),
    CurrencyData(code="MAD", num=504, scale=2, name="Moroccan dirham", symbol="DH", countries=listOf(Country(code="MA", lang="shi", name="Morocco"), Country(code="EH", lang="ar", name="Western Sahara"))),
    CurrencyData(code="MDL", num=498, scale=2, name="Moldovan leu", symbol="L", countries=listOf(Country(code="MD", lang="ro", name="Moldova"))),
    CurrencyData(code="MGA", num=969, scale=2, name="Malagasy ariary", symbol="Ar", countries=listOf(Country(code="MG", lang="mg", name="Madagascar"))),
    CurrencyData(code="MKD", num=807, scale=2, name="Macedonian denar", symbol="den", countries=listOf(Country(code="MK", lang="mk", name="North Macedonia"))),
    CurrencyData(code="MMK", num=104, scale=2, name="Myanmar kyat", symbol="Ks", countries=listOf(Country(code="MM", lang="my", name="Myanmar"))),
    CurrencyData(code="MNT", num=496, scale=2, name="Mongolian tögrög", symbol="₮", countries=listOf(Country(code="MN", lang="mn", name="Mongolia"))),
    CurrencyData(code="MOP", num=446, scale=2, name="Macanese pataca", symbol="MOP$", countries=listOf(Country(code="MO", lang="zh", name="Macau"))),
    CurrencyData(code="MRU", num=929, scale=2, name="Mauritanian ouguiya", symbol="UM", countries=listOf(Country(code="MR", lang="ff", name="Mauritania"))),
    CurrencyData(code="MUR", num=480, scale=2, name="Mauritian rupee", symbol="Rs.", countries=listOf(Country(code="MU", lang="en", name="Mauritius"))),
    CurrencyData(code="MVR", num=462, scale=2, name="Maldivian rufiyaa", symbol="MRf", countries=listOf(Country(code="", lang="", name="Maldives"))),
    CurrencyData(code="MWK", num=454, scale=2, name="Malawian kwacha", symbol="MK", countries=listOf(Country(code="MW", lang="en", name="Malawi"))),
    CurrencyData(code="MXN", num=484, scale=2, name="Mexican peso", symbol="MX$", countries=listOf(Country(code="MX", lang="es", name="Mexico"))),
    CurrencyData(code="MYR", num=458, scale=2, name="Malaysian ringgit", symbol="RM", countries=listOf(Country(code="MY", lang="en", name="Malaysia"))),
    CurrencyData(code="MZN", num=943, scale=2, name="Mozambican metical", symbol="MTn", countries=listOf(Country(code="MZ", lang="seh", name="Mozambique"))),
    CurrencyData(code="NAD", num=516, scale=2, name="Namibian dollar", symbol="N$", countries=listOf(Country(code="NA", lang="af", name="Namibia"))),
    CurrencyData(code="NGN", num=566, scale=2, name="Nigerian naira", symbol="₦", countries=listOf(Country(code="NG", lang="ig", name="Nigeria"))),
    CurrencyData(code="NIO", num=558, scale=2, name="Nicaraguan córdoba", symbol="C$", countries=listOf(Country(code="NI", lang="es", name="Nicaragua"))),
    CurrencyData(code="NOK", num=578, scale=2, name="Norwegian krone", symbol="kr", countries=listOf(Country(code="NO", lang="nn", name="Norway"), Country(code="SJ", lang="nb", name="Svalbard and Jan Mayen"), Country(code="BV", lang="", name="Bouvet Island"))),
    CurrencyData(code="NPR", num=524, scale=2, name="Nepalese rupee", symbol="Rs.", countries=listOf(Country(code="NP", lang="ne", name="Nepal"))),
    CurrencyData(code="NZD", num=554, scale=2, name="New Zealand dollar", symbol="NZ$", countries=listOf(Country(code="NZ", lang="en", name="New Zealand"), Country(code="CK", lang="en", name="Cook Islands"), Country(code="NU", lang="en", name="Niue"), Country(code="PN", lang="en", name="Pitcairn Islands"), Country(code="TK", lang="en", name="Tokelau"))),
    CurrencyData(code="OMR", num=512, scale=3, name="Omani rial", symbol="OR", countries=listOf(Country(code="OM", lang="ar", name="Oman"))),
    CurrencyData(code="PAB", num=590, scale=2, name="Panamanian balboa", symbol="B/.", countries=listOf(Country(code="PA", lang="es", name="Panama"))),
    CurrencyData(code="PEN", num=604, scale=2, name="Peruvian sol", symbol="S/.", countries=listOf(Country(code="PE", lang="qu", name="Peru"))),
    CurrencyData(code="PGK", num=598, scale=2, name="Papua New Guinean kina", symbol="K", countries=listOf(Country(code="PG", lang="en", name="Papua New Guinea"))),
    CurrencyData(code="PHP", num=608, scale=2, name="Philippine peso", symbol="₱", countries=listOf(Country(code="PH", lang="en", name="Philippines"))),
    CurrencyData(code="PKR", num=586, scale=2, name="Pakistani rupee", symbol="Rs.", countries=listOf(Country(code="PK", lang="sd", name="Pakistan"))),
    CurrencyData(code="PLN", num=985, scale=2, name="Polish złoty", symbol="zł", countries=listOf(Country(code="PL", lang="pl", name="Poland"))),
    CurrencyData(code="PYG", num=600, scale=0, name="Paraguayan guaraní", symbol="₲", countries=listOf(Country(code="PY", lang="es", name="Paraguay"))),
    CurrencyData(code="QAR", num=634, scale=2, name="Qatari riyal", symbol="QR", countries=listOf(Country(code="QA", lang="ar", name="Qatar"))),
    CurrencyData(code="RON", num=946, scale=2, name="Romanian leu", symbol="L", countries=listOf(Country(code="RO", lang="ro", name="Romania"))),
    CurrencyData(code="RSD", num=941, scale=2, name="Serbian dinar", symbol="din", countries=listOf(Country(code="RS", lang="sr", name="Serbia"))),
    CurrencyData(code="CNY", num=156, scale=2, name="Renminbi", symbol="CN¥", countries=listOf(Country(code="CN", lang="ug", name="China"))),
    CurrencyData(code="RUB", num=643, scale=2, name="Russian ruble", symbol="₽", countries=listOf(Country(code="RU", lang="os", name="Russia"))),
    CurrencyData(code="RWF", num=646, scale=0, name="Rwandan franc", symbol="FRw", countries=listOf(Country(code="RW", lang="fr", name="Rwanda"))),
    CurrencyData(code="SAR", num=682, scale=2, name="Saudi riyal", symbol="SR", countries=listOf(Country(code="SA", lang="ar", name="Saudi Arabia"))),
    CurrencyData(code="SBD", num=90, scale=2, name="Solomon Islands dollar", symbol="SI$", countries=listOf(Country(code="SB", lang="en", name="Solomon Islands"))),
    CurrencyData(code="SCR", num=690, scale=2, name="Seychelles rupee", symbol="Rs.", countries=listOf(Country(code="SC", lang="en", name="Seychelles"))),
    CurrencyData(code="SDG", num=938, scale=2, name="Sudanese pound", symbol="£SD", countries=listOf(Country(code="SD", lang="en", name="Sudan"))),
    CurrencyData(code="SEK", num=752, scale=2, name="Swedish krona", symbol="kr", countries=listOf(Country(code="SE", lang="en", name="Sweden"))),
    CurrencyData(code="SGD", num=702, scale=2, name="Singapore dollar", symbol="S$", countries=listOf(Country(code="SG", lang="en", name="Singapore"))),
    CurrencyData(code="SHP", num=654, scale=2, name="Saint Helena pound", symbol="£", countries=listOf(Country(code="SH-SH", lang="", name="Saint Helena"), Country(code="SH-AC", lang="", name="Ascension Island"))),
    CurrencyData(code="SLL", num=694, scale=2, name="Sierra Leonean leone", symbol="Le", countries=listOf(Country(code="SL", lang="en", name="Sierra Leone"))),
    CurrencyData(code="SOS", num=706, scale=2, name="Somali shilling", symbol="Sh.So.", countries=listOf(Country(code="SO", lang="so", name="Somalia"))),
    CurrencyData(code="SRD", num=968, scale=2, name="Surinamese dollar", symbol="Sr$", countries=listOf(Country(code="SR", lang="nl", name="Suriname"))),
    CurrencyData(code="SSP", num=728, scale=2, name="South Sudanese pound", symbol="SS£", countries=listOf(Country(code="SS", lang="ar", name="South Sudan"))),
    CurrencyData(code="STN", num=930, scale=2, name="São Tomé and Príncipe dobra", symbol="Db", countries=listOf(Country(code="ST", lang="pt", name="São Tomé and Príncipe"))),
    CurrencyData(code="SVC", num=222, scale=2, name="Salvadoran colón", symbol="₡", countries=listOf(Country(code="SV", lang="es", name="El Salvador"))),
    CurrencyData(code="SYP", num=760, scale=2, name="Syrian pound", symbol="LS", countries=listOf(Country(code="SY", lang="fr", name="Syria"))),
    CurrencyData(code="SZL", num=748, scale=2, name="Swazi lilangeni", symbol="L", countries=listOf(Country(code="SZ", lang="en", name="Eswatini"))),
    CurrencyData(code="THB", num=764, scale=2, name="Thai baht", symbol="฿", countries=listOf(Country(code="TH", lang="th", name="Thailand"))),
    CurrencyData(code="TJS", num=972, scale=2, name="Tajikistani somoni", symbol="SM", countries=listOf(Country(code="TJ", lang="tg", name="Tajikistan"))),
    CurrencyData(code="TMT", num=934, scale=2, name="Turkmenistan manat", symbol="m.", countries=listOf(Country(code="TM", lang="tk", name="Turkmenistan"))),
    CurrencyData(code="TND", num=788, scale=3, name="Tunisian dinar", symbol="DT", countries=listOf(Country(code="TN", lang="ar", name="Tunisia"))),
    CurrencyData(code="TOP", num=776, scale=2, name="Tongan paʻanga", symbol="T$", countries=listOf(Country(code="TO", lang="en", name="Tonga"))),
    CurrencyData(code="TRY", num=949, scale=2, name="Turkish lira", symbol="TL", countries=listOf(Country(code="TR", lang="tr", name="Turkey"))),
    CurrencyData(code="TTD", num=780, scale=2, name="Trinidad and Tobago dollar", symbol="TT$", countries=listOf(Country(code="TT", lang="en", name="Trinidad and Tobago"))),
    CurrencyData(code="TWD", num=901, scale=2, name="New Taiwan dollar", symbol="NT$", countries=listOf(Country(code="TW", lang="zh", name="Taiwan"))),
    CurrencyData(code="TZS", num=834, scale=2, name="Tanzanian shilling", symbol="TSh", countries=listOf(Country(code="TZ", lang="mas", name="Tanzania"))),
    CurrencyData(code="UAH", num=980, scale=2, name="Ukrainian hryvnia", symbol="₴", countries=listOf(Country(code="UA", lang="ru", name="Ukraine"))),
    CurrencyData(code="UGX", num=800, scale=0, name="Ugandan shilling", symbol="USh", countries=listOf(Country(code="UG", lang="en", name="Uganda"))),
    CurrencyData(code="USD", num=840, scale=2, name="United States dollar", symbol="$", countries=listOf(Country(code="US", lang="chr", name="United States"), Country(code="AS", lang="en", name="American Samoa"), Country(code="IO", lang="en", name="British Indian Ocean Territory"), Country(code="VG", lang="en", name="British Virgin Islands"), Country(code="BQ", lang="nl", name="Caribbean Netherlands"), Country(code="EC", lang="es", name="Ecuador"), Country(code="SV", lang="es", name="El Salvador"), Country(code="GU", lang="en", name="Guam"), Country(code="MH", lang="en", name="Marshall Islands"), Country(code="FM", lang="en", name="Federated States of Micronesia"), Country(code="MP", lang="en", name="Northern Mariana Islands"), Country(code="PW", lang="en", name="Palau"), Country(code="PA", lang="es", name="Panama"), Country(code="PR", lang="es", name="Puerto Rico"), Country(code="TL", lang="pt", name="Timor-Leste"), Country(code="TC", lang="en", name="Turks and Caicos Islands"), Country(code="VI", lang="en", name="U.S. Virgin Islands"), Country(code="UM", lang="en", name="United States Minor Outlying Islands"))),
    CurrencyData(code="UYU", num=858, scale=2, name="Uruguayan peso", symbol="{'$'}U", countries=listOf(Country(code="UY", lang="es", name="Uruguay"))),
    CurrencyData(code="UZS", num=860, scale=2, name="Uzbekistan som", symbol="сум", countries=listOf(Country(code="UZ", lang="uz", name="Uzbekistan"))),
    CurrencyData(code="VED", num=926, scale=2, name="Venezuelan bolívar|Venezuelan bolívar digital", symbol="Bs.", countries=listOf(Country(code="VE", lang="es", name="Venezuela"))),
    CurrencyData(code="VES", num=928, scale=2, name="Venezuelan bolívar|Venezuelan bolívar soberano", symbol="Bs.F", countries=listOf(Country(code="VE", lang="es", name="Venezuela"))),
    CurrencyData(code="VND", num=704, scale=0, name="Vietnamese đồng", symbol="₫", countries=listOf(Country(code="VN", lang="vi", name="Vietnam"))),
    CurrencyData(code="VUV", num=548, scale=0, name="Vanuatu vatu", symbol="VT", countries=listOf(Country(code="VU", lang="en", name="Vanuatu"))),
    CurrencyData(code="WST", num=882, scale=2, name="Samoan tala", symbol="T", countries=listOf(Country(code="WS", lang="en", name="Samoa"))),
    CurrencyData(code="XAF", num=950, scale=0, name="Central African CFA franc|CFA franc BEAC", symbol="Fr", countries=listOf(Country(code="CM", lang="yav", name="Cameroon"), Country(code="CF", lang="sg", name="Central African Republic"), Country(code="CG", lang="fr", name="Republic of the Congo"), Country(code="TD", lang="fr", name="Chad"), Country(code="GQ", lang="fr", name="Equatorial Guinea"), Country(code="GA", lang="fr", name="Gabon"))),
    CurrencyData(code="XCD", num=951, scale=2, name="East Caribbean dollar", symbol="$", countries=listOf(Country(code="AI", lang="en", name="Anguilla"), Country(code="AG", lang="en", name="Antigua and Barbuda"), Country(code="DM", lang="en", name="Dominica"), Country(code="GD", lang="en", name="Grenada"), Country(code="MS", lang="en", name="Montserrat"), Country(code="KN", lang="en", name="Saint Kitts and Nevis"), Country(code="LC", lang="en", name="Saint Lucia"), Country(code="VC", lang="en", name="Saint Vincent and the Grenadines"))),
    CurrencyData(code="XOF", num=952, scale=0, name="West African CFA franc|CFA franc BCEAO", symbol="₣", countries=listOf(Country(code="BJ", lang="yo", name="Benin"), Country(code="BF", lang="fr", name="Burkina Faso"), Country(code="CI", lang="fr", name="Côte d'Ivoire"), Country(code="GW", lang="pt", name="Guinea-Bissau"), Country(code="ML", lang="khq", name="Mali"), Country(code="NE", lang="fr", name="Niger"), Country(code="SN", lang="wo", name="Senegal"), Country(code="TG", lang="ee", name="Togo"))),
    CurrencyData(code="XPF", num=953, scale=0, name="CFP franc ", symbol="₣", countries=listOf(Country(code="PF", lang="fr", name="French territories of the Pacific Ocean: French Polynesia"), Country(code="NC", lang="fr", name="New Caledonia"), Country(code="WF", lang="fr", name="Wallis and Futuna"))),
    CurrencyData(code="YER", num=886, scale=2, name="Yemeni rial", symbol="YR", countries=listOf(Country(code="YE", lang="ar", name="Yemen"))),
    CurrencyData(code="ZAR", num=710, scale=2, name="South African rand", symbol="R", countries=listOf(Country(code="SZ", lang="en", name="Eswatini"), Country(code="LS", lang="en", name="Lesotho"), Country(code="NA", lang="af", name="Namibia"), Country(code="ZA", lang="af", name="South Africa"))),
    CurrencyData(code="ZMW", num=967, scale=2, name="Zambian kwacha", symbol="ZK", countries=listOf(Country(code="ZM", lang="bem", name="Zambia"))),
    CurrencyData(code="ZWL", num=932, scale=2, name="Zimbabwean dollar", symbol="Z$", countries=listOf(Country(code="ZW", lang="en", name="Zimbabwe"))),
).associateBy { it.code }

