package com.wisnu.kurniawan.wallee.foundation.currency

data class CurrencyData(
    val code: String,
    val national: String,
    val symbol: String
) {
    companion object {
        val DATA = listOf(
            CurrencyData("EUR", "Euro", "€"),
            CurrencyData("USD", "United States Dollar", "$"),
            CurrencyData("GBP", "British Pound", "£"),
            CurrencyData("CZK", "Czech Koruna", "Kč"),
            CurrencyData("TRY", "Turkish Lira", "₺"),
            CurrencyData("AED", "Emirati Dirham", "د.إ"),
            CurrencyData("AFN", "Afghanistan Afghani", "؋"),
            CurrencyData("ARS", "Argentine Peso", "$"),
            CurrencyData("AUD", "Australian Dollar", "$"),
            CurrencyData("BBD", "Barbados Dollar", "$"),
            CurrencyData("BDT", "Bangladeshi Taka", " Tk"),
            CurrencyData("BGN", "Bulgarian Lev", "лв"),
            CurrencyData("BHD", "Bahraini Dinar", "BD"),
            CurrencyData("BMD", "Bermuda Dollar", "$"),
            CurrencyData("BND", "Brunei Darussalam Dollar", "$"),
            CurrencyData("BOB", "Bolivia Bolíviano", "\$b"),
            CurrencyData("BRL", "Brazil Real", "R$"),
            CurrencyData("BTN", "Bhutanese Ngultrum", "Nu."),
            CurrencyData("BZD", "Belize Dollar", "BZ$"),
            CurrencyData("CAD", "Canada Dollar", "$"),
            CurrencyData("CHF", "Switzerland Franc", "CHF"),
            CurrencyData("CLP", "Chile Peso", "$"),
            CurrencyData("CNY", "China Yuan Renminbi", "¥"),
            CurrencyData("COP", "Colombia Peso", "$"),
            CurrencyData("CRC", "Costa Rica Colon", "₡"),
            CurrencyData("DKK", "Denmark Krone", "kr"),
            CurrencyData("DOP", "Dominican Republic Peso", "RD$"),
            CurrencyData("EGP", "Egypt Pound", "£"),
            CurrencyData("ETB", "Ethiopian Birr", "Br"),
            CurrencyData("GEL", "Georgian Lari", "₾"),
            CurrencyData("GHS", "Ghana Cedi", "¢"),
            CurrencyData("GMD", "Gambian dalasi", "D"),
            CurrencyData("GYD", "Guyana Dollar", "$"),
            CurrencyData("HKD", "Hong Kong Dollar", "$"),
            CurrencyData("HRK", "Croatia Kuna", "kn"),
            CurrencyData("HUF", "Hungary Forint", "Ft"),
            CurrencyData("IDR", "Indonesia Rupiah", "Rp"),
            CurrencyData("ILS", "Israel Shekel", "₪"),
            CurrencyData("INR", "Indian Rupee", "₹"),
            CurrencyData("ISK", "Iceland Krona", "kr"),
            CurrencyData("JMD", "Jamaica Dollar", "J$"),
            CurrencyData("JPY", "Japanese Yen", "¥"),
            CurrencyData("KES", "Kenyan Shilling", "KSh"),
            CurrencyData("KRW", "Korea (South) Won", "₩"),
            CurrencyData("KWD", "Kuwaiti Dinar", "د.ك"),
            CurrencyData("KYD", "Cayman Islands Dollar", "$"),
            CurrencyData("KZT", "Kazakhstan Tenge", "лв"),
            CurrencyData("LAK", "Laos Kip", "₭"),
            CurrencyData("LKR", "Sri Lanka Rupee", "₨"),
            CurrencyData("LRD", "Liberia Dollar", "$"),
            CurrencyData("LTL", "Lithuanian Litas", "Lt"),
            CurrencyData("MAD", "Moroccan Dirham", "MAD"),
            CurrencyData("MDL", "Moldovan Leu", "MDL"),
            CurrencyData("MKD", "Macedonia Denar", "ден"),
            CurrencyData("MNT", "Mongolia Tughrik", "₮"),
            CurrencyData("MUR", "Mauritius Rupee", "₨"),
            CurrencyData("MWK", "Malawian Kwacha", "MK"),
            CurrencyData("MXN", "Mexico Peso", "$"),
            CurrencyData("MYR", "Malaysia Ringgit", "RM"),
            CurrencyData("MZN", "Mozambique Metical", "MT"),
            CurrencyData("NAD", "Namibia Dollar", "$"),
            CurrencyData("NGN", "Nigeria Naira", "₦"),
            CurrencyData("NIO", "Nicaragua Cordoba", "C$"),
            CurrencyData("NOK", "Norway Krone", "kr"),
            CurrencyData("NPR", "Nepal Rupee", "₨"),
            CurrencyData("NZD", "New Zealand Dollar", "$"),
            CurrencyData("OMR", "Oman Rial", "﷼"),
            CurrencyData("PEN", "Peru Sol", "S/."),
            CurrencyData("PGK", "Papua New Guinean Kina", "K"),
            CurrencyData("PHP", "Philippines Peso", "₱"),
            CurrencyData("PKR", "Pakistan Rupee", "₨"),
            CurrencyData("PLN", "Poland Zloty", "zł"),
            CurrencyData("PYG", "Paraguay Guarani", "Gs"),
            CurrencyData("QAR", "Qatar Riyal", "﷼"),
            CurrencyData("RON", "Romania Leu", "lei"),
            CurrencyData("RSD", "Serbia Dinar", "Дин."),
            CurrencyData("RUB", "Russia Ruble", "₽"),
            CurrencyData("SAR", "Saudi Arabia Riyal", "﷼"),
            CurrencyData("SEK", "Sweden Krona", "kr"),
            CurrencyData("SGD", "Singapore Dollar", "$"),
            CurrencyData("SOS", "Somalia Shilling", "S"),
            CurrencyData("SRD", "Suriname Dollar", "$"),
            CurrencyData("THB", "Thailand Baht", "฿"),
            CurrencyData("TTD", "Trinidad and Tobago Dollar", "TT$"),
            CurrencyData("TWD", "Taiwan New Dollar", "NT$"),
            CurrencyData("TZS", "Tanzanian Shilling", "TSh"),
            CurrencyData("UAH", "Ukraine Hryvnia", "₴"),
            CurrencyData("UGX", "Ugandan Shilling", "USh"),
            CurrencyData("UYU", "Uruguay Peso", "\$U"),
            CurrencyData("VEF", "Venezuela Bolívar", "Bs"),
            CurrencyData("VND", "Viet Nam Dong", "₫"),
            CurrencyData("YER", "Yemen Rial", "﷼"),
            CurrencyData("ZAR", "South Africa Rand", "R")
        ).associateBy { it.code }
    }
}
